title: "Just the Docs Minimal"
description: "A minimal Jekyll site using just-the-docs"
baseurl: ""
url: "http://localhost:4000"
theme: "just-the-docs"
search_enabled: true
mermaid: 
  version: "11.6.0"