title: "OS² Demo Docs"
logo: "https://www.os2.eu/web/image/website/1/logo/OS2%20%E2%80%93%20Offentligt%20digitaliseringsf%C3%A6llesskab"
description: "A minimal Jekyll site using just-the-docs"
baseurl: ""
url: "http://localhost:4000"
theme: "just-the-docs"
search_enabled: true

mermaid: 
  version: "11.6.0"

plugins:
  - jekyll-last-modified-at 


footer_content: ""

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # your repo URL
gh_edit_branch: "main" # branch docs are served from
# gh_edit_source: docs # uncomment if your docs are in a subfolder
gh_edit_view_mode: "edit" # "tree" or "edit"

callouts:
  note:
    title: "Note"
    color: blue
  tip:
    title: "Tip"
    color: green
  important:
    title: "Important"
    color: yellow
  warning:
    title: "Warning"
    color: red