# This manifest defines:
# - A PersistentVolumeClaim for shared storage between containers and vscode (or another IDE icoul)
# - A Pod running Jekyll, mounting the shared storage

# Jekyll Pod
apiVersion: v1
kind: Pod
metadata:
  name: jekyll
spec:
  volumes:
    - name: jekyll-shared
      hostPath:
        path: /home/jmk/Repositories/jekyll-dev-setup
        type: Directory
        selinuxRelabel: "shared"
  containers:
    - name: jekyll
      image: ghcr.io/bretfisher/jekyll-serve:latest
      ports:
        - containerPort: 4000
          hostPort: 4000
      volumeMounts:
        - mountPath: /site
          name: jekyll-shared